server:
  port: 5255

spring:
  redis:
    ##redis 单机环境配置
    host: 192.168.0.25
    port: 6379
    password:
    database: 0
    ssl: false
    ##redis 集群环境配置
    #cluster:
    #  nodes: 127.0.0.1:7001,127.0.0.1:7002,127.0.0.1:7003
    #  commandTimeout: 5000
  datasource:
    url: jdbc:mysql://192.168.0.25:3306/ms_appdb?useSSL=false&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&tinyInt1isBit=false&allowMultiQueries=true&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: ms_app
    password: Ms_app2020
    driver-class-name: com.mysql.cj.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    #driver-class-name: oracle.jdbc.OracleDriver
    druid:
      # MySql、PostgreSQL校验
      validation-query: select 1
      # Oracle校验
      #validation-query: select 1 from dual


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:3031/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:V${project.version}

#ribbon配置
ribbon:
  #对当前实例的重试次数
  MaxAutoRetries: 1
  #切换实例的重试次数
  MaxAutoRetriesNextServer: 2
  #请求处理的超时时间
  ReadTimeout: 120000
  #请求连接的超时时间
  ConnectTimeout: 120000
  #对所有操作请求都进行重试
  OkToRetryOnAllOperations: true

#==================== 日志配合·标准  ============================
#日志级别
logging:
  level:
    root: info
  file: D:\\home\\logs\\sample.log
  # 修改在控制台输出的日志格式
  pattern:
    #console: %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{30} -%msg%n
  # 修改输出到文件的日志格式
    #file: %d{yyyy/MM/dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} %msg%n
# 文件分块设置
#logging.file.max-size=10MB

#
#
#seata:
#  enabled: true
#  application-id: ms-trade
#  tx-service-group: my_test_tx_group
#  enable-auto-data-source-proxy: true
#  data-source-proxy-mode: AT
#  use-jdk-proxy: false
#  excludes-for-auto-proxying: firstClassNameForExclude,secondClassNameForExclude
#  client:
#    rm:
#      async-commit-buffer-limit: 10000
#      report-retry-count: 5
#      table-meta-check-enable: false
#      report-success-enable: false
#      saga-branch-register-enable: false
#      saga-json-parser: fastjson
#      saga-retry-persist-mode-update: false
#      saga-compensate-persist-mode-update: false
#      lock:
#        retry-interval: 10
#        retry-times: 30
#        retry-policy-branch-rollback-on-conflict: true
#    tm:
#      commit-retry-count: 5
#      rollback-retry-count: 5
#      default-global-transaction-timeout: 60000
#      degrade-check: false
#      degrade-check-period: 2000
#      degrade-check-allow-times: 10
#    undo:
#      data-validation: true
#      log-serialization: jackson
#      log-table: undo_log
#      only-care-update-columns: true
#      compress:
#        enable: true
#        type: zip
#        threshold: 64k
#  service:
#    vgroup-mapping:
#      my_test_tx_group: default
#    grouplist:
#      default: 127.0.0.1:8091
#    enable-degrade: false
#    disable-global-transaction: false
#  transport:
#    shutdown:
#      wait: 3
#    thread-factory:
#      boss-thread-prefix: NettyBoss
#      worker-thread-prefix: NettyServerNIOWorker
#      server-executor-thread-prefix: NettyServerBizHandler
#      share-boss-worker: false
#      client-selector-thread-prefix: NettyClientSelector
#      client-selector-thread-size: 1
#      client-worker-thread-prefix: NettyClientWorkerThread
#      worker-thread-size: default
#      boss-thread-size: 1
#    type: TCP
#    server: NIO
#    heartbeat: true
#    serialization: seata
#    compressor: none
#    enable-client-batch-send-request: true
#  config:
#    type: file
#    consul:
#      server-addr: 127.0.0.1:8500
#    apollo:
#      apollo-meta: http://192.168.1.204:8801
#      app-id: seata-server
#      namespace: application
#      apollo-accesskey-secret: ""
#    etcd3:
#      server-addr: http://localhost:2379
#    nacos:
#      namespace: ""
#      server-addr: 127.0.0.1:8848
#      group: SEATA_GROUP
#      username: ""
#      password: ""
#    zk:
#      server-addr: 127.0.0.1:2181
#      session-timeout: 6000
#      connect-timeout: 2000
#      username: ""
#      password: ""
#    custom:
#      name: ""
#  registry:
#    type: eureka
#    load-balance: RandomLoadBalance
#    load-balance-virtual-nodes: 10
#    file:
#      name: file.conf
#    consul:
#      server-addr: 127.0.0.1:8500
#    etcd3:
#      server-addr: http://localhost:2379
#    eureka:
#      weight: 1
#      service-url: http://192.168.0.23:3031/eureka
#    nacos:
#      application: seata-server
#      server-addr: 127.0.0.1:8848
#      group : "SEATA_GROUP"
#      namespace: ""
#      username: ""
#      password: ""
#    redis:
#      server-addr: localhost:6379
#      db: 0
#      password: ""
#      timeout: 0
#    sofa:
#      server-addr: 127.0.0.1:9603
#      region: DEFAULT_ZONE
#      datacenter: DefaultDataCenter
#      group: SEATA_GROUP
#      address-wait-time: 3000
#      application: default
#    zk:
#      server-addr: 127.0.0.1:2181
#      session-timeout: 6000
#      connect-timeout: 2000
#      username: ""
#      password: ""
#    custom:
#      name: ""
#  log:
#    exception-rate: 100
